logging:
  level:
    root: INFO
server:
  servlet:
    context-path: /rest
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      data-source-properties:
        string type: unspecified
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  endpoints:
    web:
      exposure:
        include: 
          - loggers
          - health
          - metrics
  endpoint:
    loggers:
      access: unrestricted
    health:
      access: unrestricted
    metrics:
      access: unrestricted