logging:
  level:
    root: INFO
server:
  servlet:
    context-path: /rest
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: 
          - loggers
          - health
          - metrics
  endpoint:
    loggers:
      access: unrestricted
    health:
      access: unrestricted
    metrics:
      access: unrestricted