logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: info
origo:
  config:
    tables:
      eventor: Eventor-igq2qtlqone6hp26nexxeqgp7e-staging
      organisation: Organisation-igq2qtlqone6hp26nexxeqgp7e-staging
---
spring:
  config:
    acivate:
      on-profile: prod
origo:
  config:
    tables:
      eventor: 



