logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: INFO
firestore:
  credentials:
    path: origo-5f37d.json
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod