logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: 
          - loggers
          - health
          - metrics
  endpoint:
    loggers:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true