logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: ERROR
management:
  endpoints:
    web:
      exposure:
        include:
          - loggers
          - metrics
  endpoint:
    loggers:
      enabled: true
    metrics:
      enabled: true
---
spring:
  config:
    acivate:
      on-profile: staging
origo:
  config:
    tables:
      eventor: Eventor-m4hygpnfanahrmhbvxw3i4jc2a-staging
